env:
  es2020: true
  node: true
extends:
  - airbnb-base
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
settings:
  import/parsers:
    "@typescript-eslint/parser": [".ts"]
  import/resolver:
    typescript:
      alwaysTryTypes: true,
plugins:
  - "@typescript-eslint"
rules: 
  "@typescript-eslint/no-unused-vars": warn
  arrow-parens: [warn, as-needed]
  comma-dangle: [warn, never]
  import/prefer-default-export: off
  import/extensions: off
  max-classes-per-file: off
  max-len: [warn, 120]
  no-unused-vars: off
  quotes: [warn, double]
