name: CI

on:
- push
- pull_request

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v1
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install
      run: yarn
    - name: Build
      run: yarn build
    - name: Lint
      run: yarn lint
